general.import = ["~/.config/alacritty/catppuccin.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "BoldItalic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "MediumItalic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.80
blur = false

[cursor.style]
shape = "Underline"
blinking = "Always"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 3
