[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.normal]
black = "#353154"
red = "#eb6f92"
green = "#439169"
yellow = "#f6c177"
blue = "#31748f"
magenta = "#c4a7e7"
cyan = "#2f7f7d"
white = "#e0def4"

[colors.bright]
black = "#47426d"
red = "#ff80a7"
green = "#4fa87a"
yellow = "#ffd684"
blue = "#398aaa"
magenta = "#dcbbff"
cyan = "#369693"
white = "#f1efff"
[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.80
blur = true

[cursor.style]
shape = "Underline"
blinking = "Always"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 9
y = 9
