general.import = ["~/.config/alacritty/rose-pine.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.90
blur = false

[cursor.style]
shape = "Underline"
blinking = "Always"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 7
y = 5
