format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$jobs\
$status\
$character"""

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = '>'
error_symbol = '[>](red)'

[directory]
truncation_length = 3
truncation_symbol = '.. /'

[git_branch]
format = '[\($branch\)]($style)'
